version: 2

jobs:
  build:
    docker:
      - image: reactnativecommunity/react-native-android:3.1

    steps:
      - checkout

      - run:
          name: Install packages
          command: |
            apt-get update
            apt-get install patch -y

      - run:
          name: Add V8
          command: |
            yarn install

      - run:
          name: Export settings from npm package
          command: |
            npm run export_npm_env

      - run:
          name: Build React Native V8
          command: |
            scripts/build.sh

      - run:
          name: Archive
          command: |
            tar cvfz dist.tgz dist

      - store_artifacts:
          path: dist.tgz

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
